### ISSUE TITLE
material-kit-react@1.2.0 build: `npm run build-css && react-scripts build`

### ISSUE THREAD

**Issue by sujay-mahadik** [creativetimofficial/material-kit-react#43]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

After running `npm run build`
`/build` folder should be created with all minified files

# Current Behavior

```
npm run build

> material-kit-react@1.2.0 build E:\github\file-post
> npm run build-css && react-scripts build


> material-kit-react@1.2.0 build-css E:\github\file-post
> node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/

Wrote 1 CSS files to E:\github\file-post\src\
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/ipfs-api/src/utils/module-config.js:7

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-kit-react@1.2.0 build: `npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-kit-react@1.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyName\AppData\Roaming\npm-cache\_logs\2018-09-26T19_34_24_192Z-debug.log
```

# Failure Information (for bugs)

Above mentioned log file
```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle material-kit-react@1.2.0~prebuild: material-kit-react@1.2.0
6 info lifecycle material-kit-react@1.2.0~build: material-kit-react@1.2.0
7 verbose lifecycle material-kit-react@1.2.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle material-kit-react@1.2.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\github\file-post\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\xampp\php;C:\ProgramData\ComposerSetup\bin;D:\Software Installing\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jre1.8.0_171\bin;D:\Software Installing\Android Studio\jre\jre;C:\Program Files\Java\jdk-10.0.2\bin;D:\Software Installing\Android SDK\platform-tools;C:\WINDOWS\System32\OpenSSH\;D:\Software Installing\Snort\bin;C:\Program Files\nodejs\;D:\Software Installing\Gpg4win\..\GnuPG\bin;C:\Users\Sujay Mahadik\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Sujay Mahadik\AppData\Local\Programs\Python\Python36-32\;C:\Users\Sujay Mahadik\AppData\Local\Microsoft\WindowsApps;D:\opencv\build\x64\vc14\bin;C:\Users\Sujay Mahadik\AppData\Local\Microsoft\WindowsApps;C:\Users\Sujay Mahadik\AppData\Roaming\Composer\vendor\bin;D:\Software Installing\Microsoft VS Code\bin;D:\Software Installing\go-ipfs;D:\Software Installing\Snort\bin;C:\Users\Sujay Mahadik\AppData\Roaming\npm
9 verbose lifecycle material-kit-react@1.2.0~build: CWD: E:\github\file-post
10 silly lifecycle material-kit-react@1.2.0~build: Args: [ '/d /s /c', 'npm run build-css && react-scripts build' ]
11 silly lifecycle material-kit-react@1.2.0~build: Returned: code: 1  signal: null
12 info lifecycle material-kit-react@1.2.0~build: Failed to exec build script
13 verbose stack Error: material-kit-react@1.2.0 build: `npm run build-css && react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid material-kit-react@1.2.0
15 verbose cwd E:\github\file-post
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error material-kit-react@1.2.0 build: `npm run build-css && react-scripts build`
22 error Exit status 1
23 error Failed at the material-kit-react@1.2.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
## Failure Logs

Please include any relevant log snippets or files here.

**Comment by EINazare** [comment]
Hello there @sujay-mahadik ,

Thank you for your interest in working with our products.
Can you please insert your package.json file?
Also, could you please tell us if you've made changes to our product?
If I run the build command, I do not get that error.

Best,
Manu

**Comment by sujay-mahadik** [comment]
Yes!, I found out what was missing it was something related to es5 and es6 of the         `./node_modules/ipfs-api/src/utils/module-config.js:7` versions, anyways thank you for replying promptly
